### ISSUE TITLE
`new NativeEventEmitter()` warning on Android

### ISSUE THREAD

**Issue by mbuluttr** [vinzscam/react-native-file-viewer#120]
Hi. I'm trying to run the usage example in the documentation and I got this warning on Android emulator and console.

"react-native": "0.66.1",
"react-native-file-viewer": "^2.1.4",
"react-native-image-crop-picker": "^0.36.4",
"react-native-document-picker": "^7.1.1",

**Example 1** 
```
import FileViewer from "react-native-file-viewer";
import DocumentPicker from "react-native-document-picker";

try {
  const res = await DocumentPicker.pick({
    type: [DocumentPicker.types.allFiles],
  });
  await FileViewer.open(res.uri);
}
catch(e) {
  // error
}
```

**Example 2**
```
import FileViewer from "react-native-file-viewer";
import ImagePicker from "react-native-image-crop-picker";

ImagePicker.openPicker({})
  .then(image => FileViewer.open(image.path))
  .catch(error => {
    // error
  });
```

**Console output**

```
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

**Comment by djwesty** [comment]
I have the same issue too, thanks for reporting it

**Comment by DraxZh** [comment]
Same here, and I have a problem not being able to see the console log, any way to solve it?

**Comment by vinzscam** [comment]
Hi, thanks for reporting the issue. This was fixed by #126 and released in `v2.1.5`

**Comment by Critically** [comment]
Still have this warning

"react-native": "0.66.3",
"react-native-file-viewer": "^2.1.5"

**Example**
`const url =
  'https://github.com/vinzscam/react-native-file-viewer/raw/master/docs/react-native-file-viewer-certificate.pdf'`

`function getUrlExtension(url) {
  return url.split(/[#?]/)[0].split('.').pop().trim()
}`

`const extension = getUrlExtension(url)`

`// Feel free to change main path according to your requirements.`
`const localFile =${RNFS.DocumentDirectoryPath}/temporaryfile.${extension}`

`const options = {
  fromUrl: url,
  toFile: localFile
}`

`const downloadCert = () => {
  RNFS.downloadFile(options)
    .promise.then(() => FileViewer.open(localFile))
    .then(() => {
      console.log('Success')
      // success
    })
    .catch((error) => {
      console.log('Error')
      // error
    })
}`
